[build]
command = "./gradlew build"
output = "app/build/libs/app-1.0-SNAPSHOT.jar"  # Update this line

[deploy]
command = "java -jar app/build/libs/app-1.0-SNAPSHOT.jar"  # Update this line

[services]
postgresql = "postgresql-railway"  # Ensure this service is correctly configured
